---
name: hello_world_work_flow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world 2"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "Goodbye"
        shell: bash

