name: hello_world_work_flow
#sepcify the events the workflow is triggererd on
#push to the follwing brach workflow is to be trigerreed  
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # for testing purpose
jobs:
  hello:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2  #ownername/reponame@versionofaction to use, call a community action and it will cloned into the repository,chk content of  repo where wf isrunning on
      - name: hello world
        run: echo "Hello world"
        shell: bash      # use bash shell to run command ehco "hello world"
  goodbye:
    runs-on: ubuntu-lastest
    steps:
      - name: goodbye
        run: echo "Goodbye"
        shell: bash


  
